### ISSUE TITLE
renode: command not found

### ISSUE THREAD

**Issue by turbinenreiter** [carlosedp/PlatformIO-Renode-Demos#2]
Hi!

When I try to run the sample project, I get the following error message:

```
Uploading .pio/build/disco_f407vg/firmware.elf
sh: renode: command not found
*** [upload] Error 127
```

`renode` is installed on my machine manually, but vscode and platformio live in their own weird environment, I have no idea on how to control. PlatformIO claims to automatically install renode.

Do you have any idea?

I solved the problem for myself by moving back to the CLI version and using that. vscode for some reason never works for me. Leaving this in case others face the same problem.

**Comment by ivankravets** [comment]
PlatformIO comes with a pre-built Renode. Just remove all "custom" lines from `platformio.ini`.

See https://github.com/carlosedp/PlatformIO-Renode-Demos/issues/1#issuecomment-719975439
